// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7edaATqypizykmBnQjVf3d6KRsH7R6n0',
    appId: '1:334321723232:web:REPLACE_WITH_ACTUAL_WEB_APP_ID',
    messagingSenderId: '334321723232',
    projectId: 'prasanna-caterers',
    authDomain: 'prasanna-caterers.firebaseapp.com',
    storageBucket: 'prasanna-caterers.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7edaATqypizykmBnQjVf3d6KRsH7R6n0',
    appId: '1:334321723232:android:4499888808fe22edc4a005',
    messagingSenderId: '334321723232',
    projectId: 'prasanna-caterers',
    storageBucket: 'prasanna-caterers.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7edaATqypizykmBnQjVf3d6KRsH7R6n0',
    appId: '1:334321723232:ios:REPLACE_WITH_ACTUAL_IOS_APP_ID',
    messagingSenderId: '334321723232',
    projectId: 'prasanna-caterers',
    storageBucket: 'prasanna-caterers.firebasestorage.app',
    iosBundleId: 'com.finolex.mess',
  );
}
